/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) comp_foot_pos_casadi_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};

/* compute_foot_position:(i0[3],i1[3],i2[3],i3)->(o0[3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a6, a7, a8, a9;
  a0=arg[3]? arg[3][0] : 0;
  a1=1.1000000000000001e+00;
  a1=(a0<=a1);
  a2=arg[1]? arg[1][0] : 0;
  a3=cos(a2);
  a4=arg[1]? arg[1][1] : 0;
  a5=cos(a4);
  a6=(a3*a5);
  a7=1.9000000000000000e-01;
  a8=-1.9500000000000001e-01;
  a9=arg[2]? arg[2][1] : 0;
  a10=(-a9);
  a11=cos(a10);
  a12=arg[2]? arg[2][2] : 0;
  a13=(-a12);
  a14=sin(a13);
  a11=(a11*a14);
  a15=sin(a10);
  a13=cos(a13);
  a16=(a15*a13);
  a11=(a11+a16);
  a11=(a8*a11);
  a16=-2.0899999999999999e-01;
  a15=(a16*a15);
  a11=(a11+a15);
  a11=(a7+a11);
  a6=(a6*a11);
  a15=sin(a4);
  a17=(a3*a15);
  a18=arg[1]? arg[1][2] : 0;
  a19=sin(a18);
  a20=(a17*a19);
  a21=sin(a2);
  a22=cos(a18);
  a23=(a21*a22);
  a20=(a20-a23);
  a23=-4.9000000000000002e-02;
  a24=arg[2]? arg[2][0] : 0;
  a25=sin(a24);
  a26=sin(a10);
  a27=(a25*a26);
  a27=(a27*a14);
  a10=cos(a10);
  a28=(a25*a10);
  a28=(a28*a13);
  a27=(a27-a28);
  a27=(a8*a27);
  a28=-6.2000000000000000e-02;
  a29=cos(a24);
  a29=(a28*a29);
  a30=(a16*a10);
  a25=(a25*a30);
  a29=(a29-a25);
  a27=(a27+a29);
  a27=(a23+a27);
  a20=(a20*a27);
  a6=(a6+a20);
  a20=(a21*a19);
  a17=(a17*a22);
  a20=(a20+a17);
  a17=cos(a24);
  a10=(a17*a10);
  a10=(a10*a13);
  a26=(a17*a26);
  a26=(a26*a14);
  a10=(a10-a26);
  a10=(a8*a10);
  a17=(a17*a30);
  a30=sin(a24);
  a30=(a28*a30);
  a17=(a17+a30);
  a10=(a10+a17);
  a20=(a20*a10);
  a6=(a6+a20);
  a20=arg[0]? arg[0][0] : 0;
  a6=(a6+a20);
  a6=(a1?a6:0);
  a17=(!a1);
  a30=2.1000000000000001e+00;
  a30=(a0<=a30);
  a26=cos(a2);
  a14=cos(a4);
  a13=(a26*a14);
  a29=(-a9);
  a25=cos(a29);
  a31=(-a12);
  a32=sin(a31);
  a25=(a25*a32);
  a33=sin(a29);
  a31=cos(a31);
  a34=(a33*a31);
  a25=(a25+a34);
  a25=(a8*a25);
  a33=(a16*a33);
  a25=(a25+a33);
  a7=(a7+a25);
  a13=(a13*a7);
  a25=sin(a4);
  a33=(a26*a25);
  a34=sin(a18);
  a35=(a33*a34);
  a36=sin(a2);
  a37=cos(a18);
  a38=(a36*a37);
  a35=(a35-a38);
  a38=4.9000000000000002e-02;
  a39=sin(a24);
  a40=sin(a29);
  a41=(a39*a40);
  a41=(a41*a32);
  a29=cos(a29);
  a42=(a39*a29);
  a42=(a42*a31);
  a41=(a41-a42);
  a41=(a8*a41);
  a42=6.2000000000000000e-02;
  a43=cos(a24);
  a43=(a42*a43);
  a44=(a16*a29);
  a39=(a39*a44);
  a43=(a43-a39);
  a41=(a41+a43);
  a41=(a38+a41);
  a35=(a35*a41);
  a13=(a13+a35);
  a35=(a36*a34);
  a33=(a33*a37);
  a35=(a35+a33);
  a33=cos(a24);
  a29=(a33*a29);
  a29=(a29*a31);
  a40=(a33*a40);
  a40=(a40*a32);
  a29=(a29-a40);
  a29=(a8*a29);
  a33=(a33*a44);
  a44=sin(a24);
  a44=(a42*a44);
  a33=(a33+a44);
  a29=(a29+a33);
  a35=(a35*a29);
  a13=(a13+a35);
  a13=(a13+a20);
  a13=(a30?a13:0);
  a35=(!a30);
  a33=3.1000000000000001e+00;
  a0=(a0<=a33);
  a33=cos(a2);
  a44=cos(a4);
  a40=(a33*a44);
  a32=-1.9000000000000000e-01;
  a31=(-a9);
  a43=cos(a31);
  a39=(-a12);
  a45=sin(a39);
  a43=(a43*a45);
  a46=sin(a31);
  a39=cos(a39);
  a47=(a46*a39);
  a43=(a43+a47);
  a43=(a8*a43);
  a46=(a16*a46);
  a43=(a43+a46);
  a43=(a32+a43);
  a40=(a40*a43);
  a46=sin(a4);
  a47=(a33*a46);
  a48=sin(a18);
  a49=(a47*a48);
  a50=sin(a2);
  a51=cos(a18);
  a52=(a50*a51);
  a49=(a49-a52);
  a52=sin(a24);
  a53=sin(a31);
  a54=(a52*a53);
  a54=(a54*a45);
  a31=cos(a31);
  a55=(a52*a31);
  a55=(a55*a39);
  a54=(a54-a55);
  a54=(a8*a54);
  a55=cos(a24);
  a55=(a28*a55);
  a56=(a16*a31);
  a52=(a52*a56);
  a55=(a55-a52);
  a54=(a54+a55);
  a23=(a23+a54);
  a49=(a49*a23);
  a40=(a40+a49);
  a49=(a50*a48);
  a47=(a47*a51);
  a49=(a49+a47);
  a47=cos(a24);
  a31=(a47*a31);
  a31=(a31*a39);
  a53=(a47*a53);
  a53=(a53*a45);
  a31=(a31-a53);
  a31=(a8*a31);
  a47=(a47*a56);
  a56=sin(a24);
  a28=(a28*a56);
  a47=(a47+a28);
  a31=(a31+a47);
  a49=(a49*a31);
  a40=(a40+a49);
  a40=(a40+a20);
  a40=(a0?a40:0);
  a49=(!a0);
  a47=cos(a2);
  a28=cos(a4);
  a56=(a47*a28);
  a9=(-a9);
  a53=cos(a9);
  a12=(-a12);
  a45=sin(a12);
  a53=(a53*a45);
  a39=sin(a9);
  a12=cos(a12);
  a54=(a39*a12);
  a53=(a53+a54);
  a53=(a8*a53);
  a39=(a16*a39);
  a53=(a53+a39);
  a32=(a32+a53);
  a56=(a56*a32);
  a4=sin(a4);
  a53=(a47*a4);
  a39=sin(a18);
  a54=(a53*a39);
  a2=sin(a2);
  a18=cos(a18);
  a55=(a2*a18);
  a54=(a54-a55);
  a55=sin(a24);
  a52=sin(a9);
  a57=(a55*a52);
  a57=(a57*a45);
  a9=cos(a9);
  a58=(a55*a9);
  a58=(a58*a12);
  a57=(a57-a58);
  a57=(a8*a57);
  a58=cos(a24);
  a58=(a42*a58);
  a16=(a16*a9);
  a55=(a55*a16);
  a58=(a58-a55);
  a57=(a57+a58);
  a38=(a38+a57);
  a54=(a54*a38);
  a56=(a56+a54);
  a54=(a2*a39);
  a53=(a53*a18);
  a54=(a54+a53);
  a53=cos(a24);
  a9=(a53*a9);
  a9=(a9*a12);
  a52=(a53*a52);
  a52=(a52*a45);
  a9=(a9-a52);
  a8=(a8*a9);
  a53=(a53*a16);
  a24=sin(a24);
  a42=(a42*a24);
  a53=(a53+a42);
  a8=(a8+a53);
  a54=(a54*a8);
  a56=(a56+a54);
  a56=(a56+a20);
  a56=(a49?a56:0);
  a40=(a40+a56);
  a40=(a35?a40:0);
  a13=(a13+a40);
  a13=(a17?a13:0);
  a6=(a6+a13);
  if (res[0]!=0) res[0][0]=a6;
  a6=(a21*a5);
  a6=(a6*a11);
  a13=(a3*a22);
  a21=(a21*a15);
  a40=(a21*a19);
  a13=(a13+a40);
  a13=(a13*a27);
  a6=(a6+a13);
  a21=(a21*a22);
  a3=(a3*a19);
  a21=(a21-a3);
  a21=(a21*a10);
  a6=(a6+a21);
  a21=arg[0]? arg[0][1] : 0;
  a6=(a6+a21);
  a6=(a1?a6:0);
  a3=(a36*a14);
  a3=(a3*a7);
  a13=(a26*a37);
  a36=(a36*a25);
  a40=(a36*a34);
  a13=(a13+a40);
  a13=(a13*a41);
  a3=(a3+a13);
  a36=(a36*a37);
  a26=(a26*a34);
  a36=(a36-a26);
  a36=(a36*a29);
  a3=(a3+a36);
  a3=(a3+a21);
  a3=(a30?a3:0);
  a36=(a50*a44);
  a36=(a36*a43);
  a26=(a33*a51);
  a50=(a50*a46);
  a13=(a50*a48);
  a26=(a26+a13);
  a26=(a26*a23);
  a36=(a36+a26);
  a50=(a50*a51);
  a33=(a33*a48);
  a50=(a50-a33);
  a50=(a50*a31);
  a36=(a36+a50);
  a36=(a36+a21);
  a36=(a0?a36:0);
  a50=(a2*a28);
  a50=(a50*a32);
  a33=(a47*a18);
  a2=(a2*a4);
  a26=(a2*a39);
  a33=(a33+a26);
  a33=(a33*a38);
  a50=(a50+a33);
  a2=(a2*a18);
  a47=(a47*a39);
  a2=(a2-a47);
  a2=(a2*a8);
  a50=(a50+a2);
  a50=(a50+a21);
  a50=(a49?a50:0);
  a36=(a36+a50);
  a36=(a35?a36:0);
  a3=(a3+a36);
  a3=(a17?a3:0);
  a6=(a6+a3);
  if (res[0]!=0) res[0][1]=a6;
  a19=(a5*a19);
  a19=(a19*a27);
  a15=(a15*a11);
  a19=(a19-a15);
  a5=(a5*a22);
  a5=(a5*a10);
  a19=(a19+a5);
  a5=arg[0]? arg[0][2] : 0;
  a19=(a19+a5);
  a1=(a1?a19:0);
  a34=(a14*a34);
  a34=(a34*a41);
  a25=(a25*a7);
  a34=(a34-a25);
  a14=(a14*a37);
  a14=(a14*a29);
  a34=(a34+a14);
  a34=(a34+a5);
  a30=(a30?a34:0);
  a48=(a44*a48);
  a48=(a48*a23);
  a46=(a46*a43);
  a48=(a48-a46);
  a44=(a44*a51);
  a44=(a44*a31);
  a48=(a48+a44);
  a48=(a48+a5);
  a0=(a0?a48:0);
  a39=(a28*a39);
  a39=(a39*a38);
  a4=(a4*a32);
  a39=(a39-a4);
  a28=(a28*a18);
  a28=(a28*a8);
  a39=(a39+a28);
  a39=(a39+a5);
  a49=(a49?a39:0);
  a0=(a0+a49);
  a35=(a35?a0:0);
  a30=(a30+a35);
  a17=(a17?a30:0);
  a1=(a1+a17);
  if (res[0]!=0) res[0][2]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int compute_foot_position(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int compute_foot_position_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int compute_foot_position_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void compute_foot_position_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int compute_foot_position_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void compute_foot_position_release(int mem) {
}

CASADI_SYMBOL_EXPORT void compute_foot_position_incref(void) {
}

CASADI_SYMBOL_EXPORT void compute_foot_position_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int compute_foot_position_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int compute_foot_position_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real compute_foot_position_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* compute_foot_position_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* compute_foot_position_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* compute_foot_position_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* compute_foot_position_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int compute_foot_position_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int compute_foot_position_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
