/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) comp_foot_jacob_2_casadi_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[41] = {3, 18, 0, 1, 2, 3, 5, 8, 11, 11, 11, 11, 14, 17, 20, 20, 20, 20, 20, 20, 20, 0, 1, 2, 0, 1, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};

/* comp_foot_jacob_2:(i0[3],i1[3],i2[3])->(o0[3x18,20nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a5, a6, a7, a8, a9;
  a0=1.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[1]? arg[1][0] : 0;
  a1=cos(a0);
  a2=arg[1]? arg[1][2] : 0;
  a3=sin(a2);
  a4=-1.9500000000000001e-01;
  a5=arg[2]? arg[2][0] : 0;
  a6=cos(a5);
  a7=arg[2]? arg[2][1] : 0;
  a7=(-a7);
  a8=cos(a7);
  a9=(a6*a8);
  a10=arg[2]? arg[2][2] : 0;
  a10=(-a10);
  a11=cos(a10);
  a12=(a9*a11);
  a13=sin(a7);
  a14=(a6*a13);
  a15=sin(a10);
  a16=(a14*a15);
  a12=(a12-a16);
  a12=(a4*a12);
  a16=-2.0899999999999999e-01;
  a17=(a16*a8);
  a18=(a6*a17);
  a19=6.2000000000000000e-02;
  a20=sin(a5);
  a20=(a19*a20);
  a18=(a18+a20);
  a12=(a12+a18);
  a18=(a3*a12);
  a20=cos(a2);
  a21=4.9000000000000002e-02;
  a22=sin(a5);
  a23=(a22*a13);
  a24=(a23*a15);
  a25=(a22*a8);
  a26=(a25*a11);
  a24=(a24-a26);
  a24=(a4*a24);
  a26=cos(a5);
  a26=(a19*a26);
  a27=(a22*a17);
  a26=(a26-a27);
  a24=(a24+a26);
  a21=(a21+a24);
  a24=(a20*a21);
  a18=(a18-a24);
  a18=(a1*a18);
  a24=sin(a0);
  a26=arg[1]? arg[1][1] : 0;
  a27=sin(a26);
  a28=(a20*a12);
  a29=(a3*a21);
  a28=(a28+a29);
  a29=(a27*a28);
  a30=cos(a26);
  a31=1.9000000000000000e-01;
  a32=cos(a7);
  a33=(a32*a15);
  a34=sin(a7);
  a35=(a34*a11);
  a33=(a33+a35);
  a33=(a4*a33);
  a35=(a16*a34);
  a33=(a33+a35);
  a31=(a31+a33);
  a33=(a30*a31);
  a29=(a29+a33);
  a29=(a24*a29);
  a18=(a18-a29);
  if (res[0]!=0) res[0][3]=a18;
  a18=(a20*a12);
  a29=(a3*a21);
  a18=(a18+a29);
  a29=(a27*a18);
  a33=(a30*a31);
  a29=(a29+a33);
  a1=(a1*a29);
  a29=(a20*a21);
  a33=(a3*a12);
  a29=(a29-a33);
  a24=(a24*a29);
  a1=(a1-a24);
  if (res[0]!=0) res[0][4]=a1;
  a1=cos(a26);
  a24=cos(a0);
  a28=(a24*a28);
  a28=(a1*a28);
  a26=sin(a26);
  a29=(a24*a31);
  a29=(a26*a29);
  a28=(a28-a29);
  if (res[0]!=0) res[0][5]=a28;
  a0=sin(a0);
  a18=(a0*a18);
  a18=(a1*a18);
  a28=(a0*a31);
  a28=(a26*a28);
  a18=(a18-a28);
  if (res[0]!=0) res[0][6]=a18;
  a1=(a1*a31);
  a31=(a20*a12);
  a18=(a3*a21);
  a31=(a31+a18);
  a26=(a26*a31);
  a1=(a1+a26);
  a1=(-a1);
  if (res[0]!=0) res[0][7]=a1;
  a1=cos(a2);
  a26=(a0*a12);
  a31=(a24*a27);
  a18=(a31*a21);
  a26=(a26+a18);
  a26=(a1*a26);
  a2=sin(a2);
  a18=(a31*a12);
  a28=(a0*a21);
  a18=(a18-a28);
  a18=(a2*a18);
  a26=(a26-a18);
  if (res[0]!=0) res[0][8]=a26;
  a26=(a0*a27);
  a18=(a26*a21);
  a28=(a24*a12);
  a18=(a18-a28);
  a18=(a1*a18);
  a28=(a26*a12);
  a29=(a24*a21);
  a28=(a28+a29);
  a28=(a2*a28);
  a18=(a18-a28);
  if (res[0]!=0) res[0][9]=a18;
  a21=(a30*a21);
  a1=(a1*a21);
  a12=(a30*a12);
  a2=(a2*a12);
  a1=(a1-a2);
  if (res[0]!=0) res[0][10]=a1;
  a1=cos(a5);
  a2=(a0*a3);
  a12=(a31*a20);
  a2=(a2+a12);
  a12=(a19*a2);
  a12=(a1*a12);
  a21=sin(a5);
  a18=(a17*a2);
  a28=(a4*a2);
  a29=(a15*a28);
  a33=(a13*a29);
  a18=(a18-a33);
  a33=(a11*a28);
  a35=(a8*a33);
  a18=(a18+a35);
  a18=(a21*a18);
  a12=(a12-a18);
  a18=sin(a5);
  a31=(a31*a3);
  a35=(a0*a20);
  a31=(a31-a35);
  a35=(a19*a31);
  a35=(a18*a35);
  a12=(a12-a35);
  a5=cos(a5);
  a35=(a4*a31);
  a36=(a15*a35);
  a37=(a13*a36);
  a38=(a17*a31);
  a39=(a11*a35);
  a40=(a8*a39);
  a38=(a38+a40);
  a37=(a37-a38);
  a37=(a5*a37);
  a12=(a12+a37);
  if (res[0]!=0) res[0][11]=a12;
  a12=(a26*a20);
  a37=(a24*a3);
  a12=(a12-a37);
  a37=(a19*a12);
  a37=(a1*a37);
  a38=(a17*a12);
  a40=(a4*a12);
  a41=(a15*a40);
  a42=(a13*a41);
  a38=(a38-a42);
  a42=(a11*a40);
  a43=(a8*a42);
  a38=(a38+a43);
  a38=(a21*a38);
  a37=(a37-a38);
  a38=(a24*a20);
  a26=(a26*a3);
  a38=(a38+a26);
  a26=(a19*a38);
  a26=(a18*a26);
  a37=(a37-a26);
  a26=(a4*a38);
  a43=(a15*a26);
  a44=(a13*a43);
  a45=(a17*a38);
  a46=(a11*a26);
  a47=(a8*a46);
  a45=(a45+a47);
  a44=(a44-a45);
  a44=(a5*a44);
  a37=(a37+a44);
  if (res[0]!=0) res[0][12]=a37;
  a20=(a30*a20);
  a37=(a19*a20);
  a1=(a1*a37);
  a37=(a17*a20);
  a44=(a4*a20);
  a45=(a15*a44);
  a47=(a13*a45);
  a37=(a37-a47);
  a47=(a11*a44);
  a48=(a8*a47);
  a37=(a37+a48);
  a21=(a21*a37);
  a1=(a1-a21);
  a3=(a30*a3);
  a19=(a19*a3);
  a18=(a18*a19);
  a1=(a1-a18);
  a18=(a4*a3);
  a19=(a15*a18);
  a13=(a13*a19);
  a17=(a17*a3);
  a21=(a11*a18);
  a8=(a8*a21);
  a17=(a17+a8);
  a13=(a13-a17);
  a5=(a5*a13);
  a1=(a1+a5);
  if (res[0]!=0) res[0][13]=a1;
  a1=cos(a7);
  a36=(a22*a36);
  a29=(a6*a29);
  a36=(a36-a29);
  a36=(a1*a36);
  a29=sin(a7);
  a33=(a6*a33);
  a2=(a6*a2);
  a31=(a22*a31);
  a2=(a2-a31);
  a2=(a16*a2);
  a33=(a33+a2);
  a39=(a22*a39);
  a33=(a33-a39);
  a33=(a29*a33);
  a36=(a36-a33);
  a33=cos(a7);
  a24=(a24*a30);
  a39=(a16*a24);
  a24=(a4*a24);
  a2=(a11*a24);
  a39=(a39+a2);
  a39=(a33*a39);
  a36=(a36+a39);
  a7=sin(a7);
  a39=(a15*a24);
  a39=(a7*a39);
  a36=(a36-a39);
  a36=(-a36);
  if (res[0]!=0) res[0][14]=a36;
  a43=(a22*a43);
  a41=(a6*a41);
  a43=(a43-a41);
  a43=(a1*a43);
  a42=(a6*a42);
  a12=(a6*a12);
  a38=(a22*a38);
  a12=(a12-a38);
  a12=(a16*a12);
  a42=(a42+a12);
  a46=(a22*a46);
  a42=(a42-a46);
  a42=(a29*a42);
  a43=(a43-a42);
  a0=(a0*a30);
  a30=(a16*a0);
  a0=(a4*a0);
  a42=(a11*a0);
  a30=(a30+a42);
  a30=(a33*a30);
  a43=(a43+a30);
  a30=(a15*a0);
  a30=(a7*a30);
  a43=(a43-a30);
  a43=(-a43);
  if (res[0]!=0) res[0][15]=a43;
  a19=(a22*a19);
  a45=(a6*a45);
  a19=(a19-a45);
  a1=(a1*a19);
  a47=(a6*a47);
  a6=(a6*a20);
  a3=(a22*a3);
  a6=(a6-a3);
  a6=(a16*a6);
  a47=(a47+a6);
  a22=(a22*a21);
  a47=(a47-a22);
  a29=(a29*a47);
  a1=(a1-a29);
  a16=(a16*a27);
  a4=(a4*a27);
  a11=(a11*a4);
  a16=(a16+a11);
  a33=(a33*a16);
  a1=(a1-a33);
  a15=(a15*a4);
  a7=(a7*a15);
  a1=(a1+a7);
  a1=(-a1);
  if (res[0]!=0) res[0][16]=a1;
  a1=cos(a10);
  a7=(a23*a35);
  a15=(a14*a28);
  a7=(a7-a15);
  a15=(a32*a24);
  a7=(a7+a15);
  a7=(a1*a7);
  a10=sin(a10);
  a28=(a9*a28);
  a35=(a25*a35);
  a28=(a28-a35);
  a24=(a34*a24);
  a28=(a28+a24);
  a28=(a10*a28);
  a7=(a7-a28);
  a7=(-a7);
  if (res[0]!=0) res[0][17]=a7;
  a7=(a23*a26);
  a28=(a14*a40);
  a7=(a7-a28);
  a28=(a32*a0);
  a7=(a7+a28);
  a7=(a1*a7);
  a40=(a9*a40);
  a26=(a25*a26);
  a40=(a40-a26);
  a0=(a34*a0);
  a40=(a40+a0);
  a40=(a10*a40);
  a7=(a7-a40);
  a7=(-a7);
  if (res[0]!=0) res[0][18]=a7;
  a23=(a23*a18);
  a14=(a14*a44);
  a23=(a23-a14);
  a32=(a32*a4);
  a23=(a23-a32);
  a1=(a1*a23);
  a9=(a9*a44);
  a25=(a25*a18);
  a9=(a9-a25);
  a34=(a34*a4);
  a9=(a9-a34);
  a10=(a10*a9);
  a1=(a1-a10);
  a1=(-a1);
  if (res[0]!=0) res[0][19]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int comp_foot_jacob_2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int comp_foot_jacob_2_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int comp_foot_jacob_2_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void comp_foot_jacob_2_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int comp_foot_jacob_2_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void comp_foot_jacob_2_release(int mem) {
}

CASADI_SYMBOL_EXPORT void comp_foot_jacob_2_incref(void) {
}

CASADI_SYMBOL_EXPORT void comp_foot_jacob_2_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int comp_foot_jacob_2_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int comp_foot_jacob_2_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real comp_foot_jacob_2_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* comp_foot_jacob_2_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* comp_foot_jacob_2_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* comp_foot_jacob_2_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* comp_foot_jacob_2_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int comp_foot_jacob_2_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int comp_foot_jacob_2_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
