/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int compute_foot_position(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int compute_foot_position_alloc_mem(void);
int compute_foot_position_init_mem(int mem);
void compute_foot_position_free_mem(int mem);
int compute_foot_position_checkout(void);
void compute_foot_position_release(int mem);
void compute_foot_position_incref(void);
void compute_foot_position_decref(void);
casadi_int compute_foot_position_n_in(void);
casadi_int compute_foot_position_n_out(void);
casadi_real compute_foot_position_default_in(casadi_int i);
const char* compute_foot_position_name_in(casadi_int i);
const char* compute_foot_position_name_out(casadi_int i);
const casadi_int* compute_foot_position_sparsity_in(casadi_int i);
const casadi_int* compute_foot_position_sparsity_out(casadi_int i);
int compute_foot_position_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int compute_foot_position_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define compute_foot_position_SZ_ARG 4
#define compute_foot_position_SZ_RES 1
#define compute_foot_position_SZ_IW 0
#define compute_foot_position_SZ_W 59
#ifdef __cplusplus
} /* extern "C" */
#endif
