/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int comp_foot_jacob_2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int comp_foot_jacob_2_alloc_mem(void);
int comp_foot_jacob_2_init_mem(int mem);
void comp_foot_jacob_2_free_mem(int mem);
int comp_foot_jacob_2_checkout(void);
void comp_foot_jacob_2_release(int mem);
void comp_foot_jacob_2_incref(void);
void comp_foot_jacob_2_decref(void);
casadi_int comp_foot_jacob_2_n_in(void);
casadi_int comp_foot_jacob_2_n_out(void);
casadi_real comp_foot_jacob_2_default_in(casadi_int i);
const char* comp_foot_jacob_2_name_in(casadi_int i);
const char* comp_foot_jacob_2_name_out(casadi_int i);
const casadi_int* comp_foot_jacob_2_sparsity_in(casadi_int i);
const casadi_int* comp_foot_jacob_2_sparsity_out(casadi_int i);
int comp_foot_jacob_2_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int comp_foot_jacob_2_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define comp_foot_jacob_2_SZ_ARG 3
#define comp_foot_jacob_2_SZ_RES 1
#define comp_foot_jacob_2_SZ_IW 0
#define comp_foot_jacob_2_SZ_W 49
#ifdef __cplusplus
} /* extern "C" */
#endif
