/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int hkinodyn(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int hkinodyn_alloc_mem(void);
int hkinodyn_init_mem(int mem);
void hkinodyn_free_mem(int mem);
int hkinodyn_checkout(void);
void hkinodyn_release(int mem);
void hkinodyn_incref(void);
void hkinodyn_decref(void);
casadi_int hkinodyn_n_in(void);
casadi_int hkinodyn_n_out(void);
casadi_real hkinodyn_default_in(casadi_int i);
const char* hkinodyn_name_in(casadi_int i);
const char* hkinodyn_name_out(casadi_int i);
const casadi_int* hkinodyn_sparsity_in(casadi_int i);
const casadi_int* hkinodyn_sparsity_out(casadi_int i);
int hkinodyn_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int hkinodyn_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define hkinodyn_SZ_ARG 4
#define hkinodyn_SZ_RES 1
#define hkinodyn_SZ_IW 0
#define hkinodyn_SZ_W 81
#ifdef __cplusplus
} /* extern "C" */
#endif
